auction:
  # You can set custom amount using permission plugin
  # Example: astra_auctions.sell_max.10
  maxAuctionPerPlayer: 5
  # Minimum price to sell slot
  minPrice: 10
  # Maximum price to sell slot
  maxPrice: 1000000
  # Announce created slots
  announce: true
  # After this time auction will be expired
  maxTime: 999999999
sounds:
  open: item.book.page_turn
  close: item.book.page_turn
  click: ui.button.click
  fail: entity.villager.no
  success: block.note_block.chime
  sold: block.note_block.chime
buttons:
  back:
    material: IRON_DOOR
    customModelData: 1
  previous:
    material: PAPER
    customModelData: 1
  next:
    material: PAPER
    customModelData: 1
  sort:
    material: SUNFLOWER
    customModelData: 1
  aauc:
    material: DIAMOND
    customModelData: 1
  expired:
    material: EMERALD
    customModelData: 1