auction:
  # After apply design of auction will be more compact
  useCompactDesign: false
  # You can set custom amount using permission plugin
  # Example: astra_auctions.sell_max.10
  maxAuctionPerPlayer: 5
  # Minimum price to sell slot
  minPrice: 10
  # Maximum price to sell slot
  maxPrice: 1000000
  # Announce created slots
  announce: true
  # After this time auction will be expired
  maxTime: 999999999
sounds:
  open: item.book.page_turn
  close: item.book.page_turn
  click: ui.button.click
  fail: entity.villager.no
  success: block.note_block.chime
  sold: block.note_block.chime
buttons:
  back:
    material: IRON_DOOR
    customModelData: 1
  previous:
    material: ARROW
    customModelData: 1
  next:
    material: ARROW
    customModelData: 1
  sort:
    material: SUNFLOWER
    customModelData: 1
  aauc:
    material: END_CRYSTAL
    customModelData: 1
  expired:
    material: BARREL
    customModelData: 1
  border:
    material: BLACK_STAINED_GLASS_PANE
    customModelData: 1
connection:
  sqlite: true
  #mysql:
  #  database: "database_name"
  #  ip: "127.0.0.1"
  #  port: 32202
  #  username: "your_username"
  #  password: "your_password"
  #  sessionVariables:
  #  - "sql_mode=\'&enabledTLSProtocols=TLSv1.2\'"