package ru.astrainteractive.astramarket.gui.layout

import ru.astrainteractive.astramarket.api.slotInventoryLayout

internal object DefaultAuctionInventoryLayoutFactory {
    @Suppress("LongMethod")
    fun create() = slotInventoryLayout {
        row(
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI
        )
        row(
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI
        )
        row(
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI
        )
        row(
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI
        )
        row(
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI,
            AuctionSlotKey.AI
        )
        row(
            AuctionSlotKey.PR,
            AuctionSlotKey.EM,
            AuctionSlotKey.GR,
            AuctionSlotKey.AU,
            AuctionSlotKey.BA,
            AuctionSlotKey.FI,
            AuctionSlotKey.EM,
            AuctionSlotKey.EM,
            AuctionSlotKey.NE
        )
    }
}
