[versions]
# Kotlin
kotlin-version = "1.9.0"
kotlin-coroutines = "1.6.3"
kotlin-json = "1.5.0-RC"
kotlin-kaml = "0.50.0"

# Drivers
driver-jdbc = "3.36.0.3"
driver-mysql = "8.0.20"



# Minecraft
minecraft-version = "1.19.2"
minecraft-velocity = "3.1.1"
minecraft-spigot = "1.20.1-R0.1-SNAPSHOT"
minecraft-papi = "2.11.2"
minecraft-protocollib = "4.8.0"
minecraft-wg = "7.0.7"
minecraft-vault = "1.7"
minecraft-coreprotect = "21.2"
minecraft-astralibs = "3.0.0-alpha02"
minecraft-bstats = "3.0.0"
minecraft-mockbukkit = "v1.19-SNAPSHOT"

# Testing
tests-org-testing = "7.1.0"
tests-junit = "4.12"
tests-mockito = "4.0.0"
tests-junit-jupiter-api = "5.9.1"
tests-junit-bom = "5.7.0"

# Fabric
minecraft-fabric-loom = "1.0-SNAPSHOT"
minecraft-fabric-kotlin = "1.8.1+kotlin.1.7.0"
minecraft-fabric-loader = "0.14.9"
minecraft-fabric-api = "0.60.0+1.19.2"

# Forge
minecraft-forge-net = "5.1.61"
minecrft-forge-version = "1.19.2-43.1.52"

# Shadow
gradle-shadow = "7.1.2"

# BuildConfig
gradle-buildconfig = "3.1.0"

# Exposed
exposed = "0.38.1"

[libraries]
# Kotlin
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-coreJvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlin-coroutines" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin-version" }
kotlin-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-json" }
kotlin-serializationKaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kotlin-kaml" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }

# Shadow
gradle-shadow = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "gradle-shadow" }

# Drivers
driver-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "driver-jdbc" }
driver-mysql = { module = "mysql:mysql-connector-java", version.ref = "driver-mysql" }

# Testing
tests-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }

# Exposed
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }


# Minecraft
minecraft-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "minecraft-spigot" }
minecraft-spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "minecraft-spigot" }
minecraft-spigot-core = { module = "org.spigotmc:spigot", version.ref = "minecraft-spigot" }
minecraft-velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "minecraft-velocity" }
minecraft-protocollib = { module = "com.comphenix.protocol:ProtocolLib", version.ref = "minecraft-protocollib" }
minecraft-papi = { module = "me.clip:placeholderapi", version.ref = "minecraft-papi" }
minecraft-vaultapi = { module = "com.github.MilkBowl:VaultAPI", version.ref = "minecraft-vault" }
minecraft-bstats = { module = "org.bstats:bstats-bukkit", version.ref = "minecraft-bstats" }
minecraft-mockbukkit = { module = "com.github.MockBukkit:MockBukkit", version.ref = "minecraft-mockbukkit" }

# klibs
klibs-kdi = { module = "ru.astrainteractive.klibs:kdi", version.strictly = "1.1.0" }
klibs-mikro = { module = "ru.astrainteractive.klibs:mikro-core", version.strictly = "1.4.0" }

# AstraLibs
minecraft-astralibs-orm = { module = "ru.astrainteractive.astralibs:orm", version.ref = "minecraft-astralibs" }
minecraft-astralibs-core = { module = "ru.astrainteractive.astralibs:core", version.ref = "minecraft-astralibs" }
minecraft-astralibs-menu-bukkit = { module = "ru.astrainteractive.astralibs:menu-bukkit", version.ref = "minecraft-astralibs" }
minecraft-astralibs-core-bukkit = { module = "ru.astrainteractive.astralibs:core-bukkit", version.ref = "minecraft-astralibs" }

# Fabric
minecraft-fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "minecraft-fabric-kotlin" }
minecraft-fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "minecraft-fabric-loader" }
minecraft-fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "minecraft-fabric-api" }
minecraft-mojang = { module = "com.mojang:minecraft", version.ref = "minecraft-version" }

[bundles]
exposed = ["exposed-java-time", "exposed-jdbc", "exposed-dao", "exposed-core"]
minecraft-bukkit = ["minecraft-paper-api", "minecraft-spigot-api", "minecraft-spigot-core", "minecraft-vaultapi", "minecraft-papi"]
testing-kotlin = ["kotlin-coroutines-core", "kotlin-coroutines-coreJvm", "driver-jdbc", "driver-mysql", "kotlin-serialization", "kotlin-serializationJson"]
kotlin = ["kotlin-coroutines-core", "kotlin-coroutines-coreJvm", "kotlin-serialization", "kotlin-serializationJson", "kotlin-serializationKaml", "kotlin-gradle"]


[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
kotlin-gradle = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }

# Minecraft
minecraft-fabric-loom = { id = "fabric-loom", version.ref = "minecraft-fabric-loom" }
minecraft-forge-net = { id = "net.minecraftforge.gradle", version.ref = "minecraft-forge-net" }

# Gradle
gradle-shadow = { id = "com.github.johnrengelman.shadow", version.ref = "gradle-shadow" }
gradle-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gradle-buildconfig" }