name: "detekt-validation"
on:
  workflow_call:
jobs:
  build:
    name: Build project with gradle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: "bukkit"
            task: ":instances:bukkit:build"
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 21
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: ${{ matrix.task }} --stacktrace
